name: 测试构建

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Test build
      run: |
        echo "Starting build test..."
        pyinstaller --name=test-converter --onefile --clean yaml_to_v2rayn.py
        
    - name: Check result
      run: |
        if (Test-Path "dist/test-converter.exe") {
          $size = (Get-Item "dist/test-converter.exe").Length / 1MB
          Write-Host "Build successful! Size: $([math]::Round($size, 1)) MB"
          ls dist/
        } else {
          Write-Host "Build failed!"
          exit 1
        }
      shell: powershell
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-build
        path: dist/test-converter.exe